### ISSUE TITLE
Alternative to sessionStorage

### ISSUE THREAD

**Issue by plynchnlm** [smart-on-fhir/client-js#109]
Is there anyway to tell client-js not to use sessionStorage?

In IE and certain versions of Edge, sessionStorage gets dropped when navigating between "security zones", which are sometimes configured by organization policy.  So if the website doing the launching falls into a different zone (based on domain name) than the website hosting the SMART app, client-js finds that it has no state when it gets back to the SMART app.

Reference:  https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-known-issues-ie-edge-browsers

In our case, I could work around this by moving one website so it has the same domain name as the other, but I am wondering if there might be some option to pass into client-js that could solve this.

**Comment by vlad-ignatov** [comment]
There are some global settings - `FHIR.oauth2.settings.fullSessionStorageSupport` and `FHIR.oauth2.settings.replaceBrowserHistory`. You can try to flip these before making any other calls to the library and see if that affects your case.

However, I'm not sure I understand what the issue is. What do you mean by "website doing the launching"?

The state is supposed to be shared between the launch URL and the redirect URL and these should already be in the same domain.

- If this is an issue that happens in real EHR it should be up to their developers to configure those zones properly
- If this is an issue that happens in development and you are using a launcher like https://launch.smarthealthit.org, then adding launch.smarthealthit.org to the same zone sounds like the right thing to do
- In any other case it should just work, unless I am missing something?

**Comment by plynchnlm** [comment]
The "website doing the launching" is the launcher, e.g. https://launch.smarthealthit.org.  We are actually running our own copy of that, in our organization's domain, so from IE's perspective it is in the local intranet zone.  Our SMART app was on GitHub Pages, which is in a different security zone, and hence the problem.  I suppose you are right that in a real EHR, the zones could be modified.  For our demo app, we would have tell people in our organization either to add GitHub Pages to the local zone, or (more simply) just warn them not to use IE.  We ended up solving it by moving off GitHub Pages and hosting the SMART app website ourselves, so now both the launcher and the app are in the same zone.

**Comment by vlad-ignatov** [comment]
Great. So I'm closing this now but feel free to reopen if needed.
