### ISSUE TITLE
Patch patient using Client-js 

### ISSUE THREAD

**Issue by usmanbahadur** [smart-on-fhir/client-js#117]
I am looking to partially update a patient and FHIR documentation suggest that [FHIR PATCH](https://www.hl7.org/fhir/http.html#patch) should be used for this purpose,Currently there is no PATCH method in Client.js. 
 Will the FHIR Client be updated so that users can support partial update of a patient rather than a complete update of a patient as the current Update overwrite the existing patient data from FHIR Server.
 it will be extremely useful to have PATCH in FHIR Client, thanks.

**Comment by vlad-ignatov** [comment]
This is perfectly doable using the current API. You can pass a `method` option like so:
```js
client.request({
    url: "Patient/123",
    method: "PATCH",
    body: "{ json data... }",
    headers: {
        "Content-Type": "application/json"
    }
    // , other request options...
}); 
```

`client.request` is the only method that actually makes requests and others like `create` or `update` are just shortcuts for the most common use cases that are calling `request` internally. For example see [how update is implemented](https://github.com/smart-on-fhir/client-js/blob/master/src/Client.ts#L673-L698). However, since `patch` is not that common and it is quite easy to do that like in the example above, I don't think its worth adding a dedicated method for that unless many people request it.

**Comment by usmanbahadur** [comment]
Issue Fixed Thanks.

**Comment by MrSerWin** [comment]
@usmanbahadur can you please share your solution? 
I couln'd resolve this problem.
