### ISSUE TITLE
Access V2 version of client

### ISSUE THREAD

**Issue by vagarwal77** [smart-on-fhir/client-js#128]
I am seeing the announcement for V2. http://docs.smarthealthit.org/client-js/v2.html. but could not found the repo. 

Please suggest

**Comment by vlad-ignatov** [comment]
This IS the repo and it is currently at v2 (which is simply the major package version released on NPM). Versions 1XX are no longer supported/maintained.

Since v1 is still being used in some legacy apps, we are keeping the page at http://docs.smarthealthit.org/client-js/v2.html as an incentive, to promote the benefits of upgrading. We may soon remove that page though, as it is slowly getting out of date.
