### ISSUE TITLE
SMART Client library should not assume access token formats

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/client-js#28]
We accidentally introduced an assumption about access token format in:

https://github.com/smart-on-fhir/client-js/blame/master/src/client/bb-client.js#L298-L302

@zplata do you have ideas about how to rewrite this to use the `expires` property of the access token response (which we do standardize) instead of assuming that the access token itself is a JWT with claims?

**Comment by zplata** [comment]
@jmandel Sorry for the late response! As you mentioned, we could possibly just use the `expires_in` property of the tokenResponse we get sent back from `getPreviousToken()`,  rather than the current method of reading the exp from a JWT, still with the assumption that this will return an amount in seconds. I can find some time soon here to make this change.

**Comment by yunwwang** [comment]
Is there a timeline when this will be fix?

**Comment by vlad-ignatov** [comment]
I am closing this as no longer relevant to the current version.
