### ISSUE TITLE
Is this project still maintained? If not, which fork to use?

### ISSUE THREAD

**Issue by col-panic** [smart-on-fhir/client-js#34]
Could the owners of this project please give a short notice on whether this project is still maintained, and if not, which of the forks is to be used as a replacement! 

Thanks a lot

**Comment by jpdimond** [comment]
Yes, this would be super helpful please!

**Comment by vlad-ignatov** [comment]
The project is still maintained but I would say it has not been our highest priority lately. Do you have any particular reason for asking this or an issue that prevents you from using it?

**Comment by col-panic** [comment]
Hey @vlad-ignatov thanks for your feedback. 

Yes, its on one part:  https://github.com/smart-on-fhir/client-js/issues/24 containing a solution to https://github.com/smart-on-fhir/client-js/issues/32 . Could you provide a new version that contains the current fhir.js client? 

And on the other part: As I  rely on your library in https://www.npmjs.com/package/@col.panic/vue-es, I'm interested in the "general health" of this project!

**Comment by vlad-ignatov** [comment]
Well..., after long consideration, I think its about time to revamp this project. I've used this library for many years but now that I have to maintain it, I found out how outdated it is. That is why I started working on new version at https://github.com/smart-on-fhir/client-ts

I need a little more time to put together the initial version that is ready for contributions. Meanwhile, if you have general issues with the current library or feature requests, now would be the time to describe them at https://github.com/smart-on-fhir/client-ts/issues.

**Comment by col-panic** [comment]
It's really great to see the project moving forward again!

**Comment by vlad-ignatov** [comment]
Check out the latest version (https://docs.smarthealthit.org/client-js/). We want to move away from fhir.js, but at least now it is up to you to decide what fhir.js version to use.

**Comment by bforbis** [comment]
@vlad-ignatov will this JS project be replaced by [client-ts](https://github.com/smart-on-fhir/client-ts)? My organization is interested in writing all of our code in Typescript, so having typescript support would be great for us.

**Comment by vlad-ignatov** [comment]
@bforbis Not in the near future. [client-ts](https://github.com/smart-on-fhir/client-ts) was a version of client-js written in TypeScript, plus a few new features. However, client-js evolved a lot since then and supports many things that are missing in client-ts. It is our mainstream client and the one that should be used in production.

We do want to switch to TypeScript but it is too early yet. For now we stick to JS is because we have some contributors that prefer it. Also, this library is very dynamic by nature and doesn't fit very well to a strictly typed language. Some parts of it cover different environments (Browser or Node) or work across different frames or windows (we are going to add popup authentication soon). We are also depending on `babel-preset-env` to handle our polyfills...

That said, we want to keep it simple for now. There are some big additions planned (like the popup auth or the multi-server configuration from client-ts. Once everything is in place and stable, we will try to switch to TypeScript.

This project is maintained, so I am now closing this.
