### ISSUE TITLE
The latest version of browserify produces incompatible code for IE10

### ISSUE THREAD

**Issue by kolkheang** [smart-on-fhir/client-js#43]
Version 16.2.3 of `browserify` npm package included as a dependency of this project does not generate code that is compatible with IE10.

When `/dist/fhir-client.js` [file](https://github.com/smart-on-fhir/client-js/blob/master/dist/fhir-client.js) is loaded in an IE10 environment, the following error is produced.

Line: 8961
> Object doesn't support property or method 'write'

**Comment by kolkheang** [comment]
Version 13.3.0 worked last time I looked into this. https://github.com/cerner/client-js/pull/10

**Comment by kolkheang** [comment]
@vlad-ignatov 
Would you be able to downgrade `browserify` to `13.3.0` until we deprecate IE 10?

**Comment by vlad-ignatov** [comment]
That seem impossible at his point without breaking other things. If it is critical, I'd suggest downgrading to older version of the `fhirclient`.

Otherwise, all our efforts are currently going into the next version, which should be released this month and include IE 10 support, along with lots of new features. Check out http://docs.smarthealthit.org/client-js/v2.html and http://docs.smarthealthit.org/client-js/. It will be very important for us to verify that this works with Cerner.

When do you plan to deprecate IE 10 BTW?

**Comment by kolkheang** [comment]
Thanks @vlad-ignatov for making this new version supports IE10.  We still have a lot of people using IE10.  It's not going away anytime soon.  I really don't know when we will stop supporting IE10.

My team and I are happy to test this new version of the library.

**Comment by vlad-ignatov** [comment]
The older version is no longer maintained and the new versions should work in IE10. That said, this issue is no longer relevant. Feel free to open new one if you have problems with `2.2.0+`.
