### ISSUE TITLE
patient read api does not return 404 error

### ISSUE THREAD

**Issue by BS062721** [smart-on-fhir/client-js#44]
we're using patient read api to get patient demographic data, when patient id is invalid backend FHIR api returns 404 error which we can see in our console but fhirClient does not return proper error code, which we point down to this line: https://github.com/smart-on-fhir/client-js/blob/master/src/client/client.js#L102

any reasons why we're not returning proper error code?

**Comment by BS062721** [comment]
CC : @vlad-ignatov

**Comment by BS062721** [comment]
@vlad-ignatov do you have any information on this?

**Comment by vlad-ignatov** [comment]
As far as I can tell, the only reason is that this is trying to be a higher level abstraction of those requests. Instead of returning responses and response codes, it resolves with data object or rejects with error message. If your promise chain is rejected you get an error message and the "on success code" will not be executed anyway.

This seems to work well enough for everybody, unless you have some very specific way of consuming the response results. Can you specify what "returning proper error code" means in your case? Perhaps an example of what you are trying to do would help.

**Comment by BS062721** [comment]
@vlad-ignatov we are consuming different APIs (patient and encounter) using FHIR client, and based on different error scenarios we have different workflows, not able to get proper error response in this particular scenario kind of disrupt the workflow

**Comment by vlad-ignatov** [comment]
I understand that, but it would help if you can define "proper error response".

**Comment by SA030800** [comment]
To add on @BS062721  comment, is an error status is not returned we wouldn't know it fails because of some server error(500) or because we are providing invalid data(400) or the resource is not found(404) etc. so we are unable to give a proper error message to the end user.

On another note: the search api's seems to return an error with error status it is just the read api which is not returning  the error status

**Comment by vlad-ignatov** [comment]
I agree that this needs to be fixed. The hard part though, is to figure out how to do that without breaking existing apps too much.

Looking at the code, I can see that a request promise can be rejected with different arguments - string messages, error instances, jQuery XHR objects... It would be nice if we could unify this and always return an object with the same shape.

What are the exact properties that you expect to find in an object, representing a failed response?

**Comment by BS062721** [comment]
for all other scenarios we are getting error response status property which gives us the proper error code for given scenario.

for example something like **error.status = 400** then we parse error response based on code

**Comment by vlad-ignatov** [comment]
This was an issue with the older version of the client and its integration with fhir.js. We have new versions now, and they should reject with [HttpError](https://github.com/smart-on-fhir/client-js/blob/master/src/HttpError.js) in such cases.

I am closing this now, but feel free to open new one if you have issues with the newer versions.
