### ISSUE TITLE
Publish beta to npm with beta tag

### ISSUE THREAD

**Issue by joeldenning** [smart-on-fhir/client-js#49]
Hi there 👋 

I'm one of the devs working on OpenMRS' EMR system. We're starting a redesign of the frontend and are exploring if/how much/what it would take to use smart-on-fhir. Main limitation is that openmrs backend doesn't have full support for it.

I'm glad to see that v2 of this project uses Promises instead of jquery deferred objects and am excited that this repo has active development.

It would be helpful to publish v2 to npm with a beta [npm dist-tag](https://docs.npmjs.com/cli/dist-tag) so that consumers can easier control upgrades to new versions of the beta. Additionally it would let my npm install only include the built files and runtime dependencies instead of how it currently installs all the babel and other dependencies that are specified in the shrinkwrap.

install from npm:
<img width="585" alt="Screen Shot 2019-06-11 at 7 01 59 PM" src="https://user-images.githubusercontent.com/5524384/59288180-d261c680-8c7b-11e9-82b2-73964c45bc69.png">

install from github:
<img width="613" alt="Screen Shot 2019-06-11 at 7 05 25 PM" src="https://user-images.githubusercontent.com/5524384/59288208-e4436980-8c7b-11e9-94c2-845435bf026d.png">

**Comment by vlad-ignatov** [comment]
Hi @joeldenning

The first example you posted (install from npm) installs the old version. That was simple, because it was only publishing the built files.

v2 is different, because we also publish the source (to be used in Node) and a few other stuff. We are looking for a way to optimize that...

As for the "dev" tag, we did actually publish it on NPM as `fhirclient@dev`, but then we quickly realized that it wasn't the best idea. The code is still changing too frequently and we can't keep it up to date on `npm`. For now, the most convenient way of using it seems to be the old-fashion way:
```html
<script src="https://combinatronics.com/smart-on-fhir/client-js/master/build/fhir-client.js"></script> 
```
Note that this link will always point to the latest build pushed on GitHub.

**Comment by joeldenning** [comment]
Thanks for the response. I disagree that you can't publish betas, since it's well understood that betas can have breaking changes before the final release. (I do this in many of my projects - [example](https://github.com/CanopyTax/single-spa-angular/releases)). However, it's your project and I respect that 😄 . I appreciate the work you have put into it.
