### ISSUE TITLE
Publish version that does not include core-js

### ISSUE THREAD

**Issue by joeldenning** [smart-on-fhir/client-js#50]
I'd prefer to be able to choose whether to include core-js into my application, in favor of choosing whether/what/how to polyfill. After cloning this repo and removing core-js, it reduced the prod bundle size for v2 from 100kb to 50kb -- would be nice if I had the choice to use fhir-client without those extra 50kb

**Comment by vlad-ignatov** [comment]
Yes, that will be possible! This is still a work in in progress, thus not documented yet but I pushed some changes so that you can give it a try. The idea is that polyfilling should be automatic and all you need to do is change the "browserlist" [here](https://github.com/smart-on-fhir/client-js/blob/master/package.json#L55-L60) and run `npm run build` (and do not commit those changes off course). The code is still changing so we shouldn't talk in numbers before the release, but just for reference, when I tried that yesterday with `"browserlist": [ "last 2 Chrome versions" ]` , the production build was 25.2K (or 8.7K with gzip)!

This project will be stuck with IE10 for a while (until the US healthcare upgrades every PC and then EHR vendors embed something newer in their EHRs). This could take another 5 years! The worst part is that this restriction also applies to the SMART App developers if they want to deploy their apps to those EHRs... That said, you are probably one of the few lucky developers out there! I hope you can understand why we do not intend to ship a "pure/modern" bundle at this point (but we will have the "browser list" feature documented).

**Comment by joeldenning** [comment]
👍 sounds good. I would add that when you add this to the project, it would be preferred to not have to clone + build from source in order to get a version without core-js in it. Browserslist and @babel/preset-env are usually not run on any projects within node_modules, since [babel-loader discourages compilation of node_modules](https://github.com/babel/babel-loader#usage) (rollup-plugin-babel, too). So I don't think it will be as easy as just npm installing the lib and then applying your browserslist to it -- the files you publish to npm will have to choose a browsers list of their own to support, that is different from the browserslist of your consumers.

So a separate file in the published npm directories would be amazing, along with a lowest-common-denominator browserslist that is used to build the published files.

**Comment by vlad-ignatov** [comment]
OK, I think I see where the confusion is coming from. This is just a global library that should be included via script tag. It cannot be imported or required (except on the back-end).

However, you are not the only one to assume that it should be usable as a module. There is certain demand for that, so I'm trying to make it. As you might imagine, that changes a lot so I'm not sure if we can do it for v2.0.
