### ISSUE TITLE
Implementation of a client-dart?

### ISSUE THREAD

**Issue by alekline** [smart-on-fhir/client-js#53]
Hi all,

This might not be the best way of asking, because it is not really an issue, so sorry about that, I can start a thread in a more appropriate place if you point me there.

I am planning to start writing a client based on Dart, but with all the great work punt into other clients, I am curious what should be my starting point, either this [client-js](https://github.com/smart-on-fhir/client-js) or the [client-ts](https://github.com/smart-on-fhir/client-ts)

Thank you

**Comment by vlad-ignatov** [comment]
`client-js` is the complete solution. `client-ts` was just an experimental attempt  to replace the old version of client-js but now that we released v2, `client-ts` is obsolete and will probably be removed.
The same applies to [client-node](https://github.com/smart-on-fhir/client-node). Basically, most of the code from `client-ts` and `client-node` is now integrated into `client-js`.

That said, `client-node`, and even `client-ts` might be easier to start with, because they are smaller and  written in typescript and as such, they can be easier to reason about.

**Comment by alekline** [comment]
Thank you  Vlad!

You guys are doing great work there!
