### ISSUE TITLE
TS4090: Conflicting definitions for 'node'

### ISSUE THREAD

**Issue by SvetlozarValchev** [smart-on-fhir/client-js#70]
I'm running Aurelia 1.3.1, this happens on clean install.

If I have a definition in packages.json  `"@types/node": "^10.11.6"`, the following error will appear when trying to run the framework:

`TS4090: Conflicting definitions for 'node' found at 'D:/dev/my_project/node_modules/@types/node/ts3.2/index.d.ts' and 'D:/dev/my_project/node_modules/fhirclient/node_modules/@types/node/ts3.5/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.`

The bug is intermittent, as it sometimes may not appear. Deleting the 'node' folder from either place stops the error from appearing.

**Comment by SvetlozarValchev** [comment]
Updating to latest Node.js (12.14.1) fixed the issue, but since the bug itself is intermittent, I'll be following closely if the fix is permanent. 

The node typings should be removed from fhirclient's node_modules, as it will cause more problems than it will solve.

**Comment by vlad-ignatov** [comment]
This appears to be a common problem in TypeScript. Most libraries avoid it by using `"@types/node": "*"`, but that is not applicable here because we depend on features not available before Node 10.

I just released `v2.3.1`, where the node types were moved to `peerDependencies`. I expect that to work fine so I'm closing the issue but feel free to reopen it if needed.
