### ISSUE TITLE
No token when launching from within EHR sandbox

### ISSUE THREAD

**Issue by admah** [smart-on-fhir/client-js#75]
We're trying to load the application within Epic's AppOrchard sandbox and keep running into an issue where the OAuth flow is aborted before getting a token. The same issue is not happening in EHRs opening in their own tabs or in standalone mode.

For the SMART auth flow, I originally used `init` which kept caching the initial result without a token response. In light of that, I switched back to using `authorize` and then `ready`.

Then, I noticed a few things that still were causing some issues:

1) in the `authorize` method in smart.js `params.target` is always undefined instead of having a default as specified in the docs. Would this cause logic problems further down the line?

2) in the `authorize` method in smart.js on line 343, I think it should be `if (win == self) {` instead of `if (win !== self) {`.  Without this, it doesn't seem like the event listener would get added correctly.

3) in the `completeAuth` method  in smart.js on line 472, the `parent.postMessage` event is either not happening or there is an issue with the listener. I tried to substitute that for every possibility from the 'postMessage' API, but nothing seemed to work there. By moving the `onMessage` functionality in there and bypassing the event, my app was able to successfully authenticate in the EHR sandbox.

**Comment by vlad-ignatov** [comment]
I'm sorry to hear that you are having issues with this. Unfortunately, it might be very difficult to reproduce. What are your settings? Are you using `target` or `completeInTarget`? What happens if you use `completeInTarget: true`?

As for the above questions:
1. In fact, the `target` option defaults to `undefined`, but that should result in the same behavior as `_self`. It is easier for people to understand that if we say in the docs that the default is "_self".
2. If `win == self`, then there is no need for `postMessage`. We are just using normal redirects then...
3. I am not even sure I understand this one.

So far, my only theory about what might be happening is this:
1. The `authorize` function is called from a page that is loaded in an iframe. 
2. By the time we get to `completeAuth` the script detects that we are in an iframe and does 2 things:
    2.1. Sends a post message to it's parent (assuming that you have control over that window, but you do not)
    2.2. Exits early, assuming that the parent will receive that post message and complete the auth.

The way to avoid that would be to use  `{ completeInTarget: true }` even if your `target` is `_self` or `undefined` (or points to the current window in some other way).

I have had similar issue here - https://codesandbox.io/s/fhir-client-typescript-react-spa-4e7rl Note the comments in `index.tsx`.

**Comment by admah** [comment]
@vlad-ignatov that did fix the issue. Thank you so much for the explanation!

**Comment by nakker** [comment]
Sorry to post on a closed topic. I ran into the same issue, it took me a good day or two to track down. The issue #3 Admah pointed out seems to be the cause. Since I would assume fhir-client might be broadly used against the Epic App Orchard in an EHR launch context (in an iframe) I would suggest adding some documentation around this argument. 

For posterity, the solution is to add the argument to the authorize call here

      FHIR.oauth2.authorize({
        'client_id': xxx,
        'scope':  xxx,
        'completeInTarget': true
    });
