### ISSUE TITLE
URL introspection?

### ISSUE THREAD

**Issue by awatson1978** [smart-on-fhir/client-js#80]
Hello,
Is there a way to introspect the URL that `fhirclient` is current set to?  I'm asking in regards to multi-vendor applications, and how to flex the search queries based on an incoming `iss` URL parameter.  I'm trying to do something like the following:

```js
import { oauth2 as SMART } from "fhirclient";

// assuming that SMART.ready() has been called already
function fetchSomeData(){
  const observationQuery = new URLSearchParams();
  console.log('Observations Query', observationQuery);

  // FEATURE REQUEST:  could we have something like the following?  
  let url = SMART.getCurrentUrl();
  if(url.includes("epic")){
    observationQuery.set("patient", client.patient.id);
  } else if (url.includes("cerner")){
      observationQuery.set("subject", client.patient.id);
  } 
  
  let observationUrl = 'Observation?' + observationQuery.toString()
  console.log('observationUrl', observationUrl);
    
  client.request(observationUrl, {
    pageLimit: 0,
    flat: true
  }).then(observations => {
   doSomeStuff(observations)
  });
}
```

Is there are alternative approach or workaround that can achieve the same thing?  

This is a real world example, by the way.  Where Cerner wants to normalize the query parameters to use the `patient` search alias, while Epic is adhering more to FHIR schema and ignoring the search option alias.
Thanks!!!

**Comment by vlad-ignatov** [comment]
Unfortunately I won't be able to consider this soon (too many other projects in the queue). However, I think `client.state.serverUrl` is what you are looking for.

FYI: Yo can find a lot in `client.state` - https://github.com/smart-on-fhir/client-js/blob/master/src/types.d.ts#L226-L310

**Comment by vlad-ignatov** [comment]
Having something like `SMART.getCurrentUrl();` is not possible because that would be a "global level" method. One can have different `Client` instances for different server URLs, so this should be a client method. Also, there could be other state properties that you might be interested in.

With that said, in `v2.3.5` there is new client method called `getState()`. Examples:
```js
client.getState(); // -> the entire state object
client.getState("serverUrl"); // -> the URL we are connected to
client.getState("tokenResponse.patient"); // -> The selected patient ID (if any)
```
Note that trying to access `client.state.tokenResponse.patient` directly can throw an error if there is no `tokenResponse`. If you use `client.getState("tokenResponse.patient");` instead, it should just return `undefined` (without throwing an error) which should be more convenient.

**Comment by plynchnlm** [comment]
I was looking for this too.  Thanks for posting the "client.state.serverUrl" solution!
