### ISSUE TITLE
Smart Auth Basic Auth popup appears if token has expired

### ISSUE THREAD

**Issue by SvetlozarValchev** [smart-on-fhir/client-js#81]
Hi,

It seems that sometimes when the token has expired, basic auth popup will appear asking for credentials: 
![image](https://user-images.githubusercontent.com/446056/82449854-838bf600-9ab4-11ea-938c-33923d7ae7c4.png)

**Comment by vlad-ignatov** [comment]
This is probably happening if the server replies with a `WWW-Authenticate` header. The browser detects that and shows that log-in prompt. The library has nothing to do with that.

The server can either support SMART, or have no authentication at all. In these cases you should be able to use this library. You can also support basic auth or some proprietary authentication, but then you don't really need this library. If you do support SMART, then you SHOULD disable the basic authentication so that they don't conflict with each other as we are seeing here.

**Comment by SvetlozarValchev** [comment]
Ok, thanks, we have a mixed environment where we have to support legacy (basic auth) together with new auth (SMART Auth), so it's not really feasible at the moment, but I'll look for alternatives. 
I read that you can stop it from appearing by either sending request header 'X-Requested-With', 'XMLHttpRequest' in the ajax request or by modifying it server-side to not send WWW-Authenticate header.

**Comment by vlad-ignatov** [comment]
Please also try version `2.3.5`. I am closing this now but feel free to reopen if needed.
