### ISSUE TITLE
Unable to refresh token due to cors response header Access-Control-Allow-Origin set to * and withCredentials attribute

### ISSUE THREAD

**Issue by kolkheang** [smart-on-fhir/client-js#83]
We are unable to refresh the token due to CORS and the `credentials: include` option in the request [here](https://github.com/smart-on-fhir/client-js/blob/master/src/Client.ts#L962) from the client side. 

```
Access to XMLHttpRequest at 'https://example-authorization-endpoint.com/protocols/oauth2/profiles/smart-v1/token' from origin 'http://origin-endpoint.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

**Comment by vlad-ignatov** [comment]
This should also be fixed in the latest version (2.3.8) in a different way. The refresh token requests will now be sent without credentials. In the rare cases when the auth server requires the app to send cookies, developers will have to configure the client to do so (for example by setting `FHIR.oauth2.settings.refreshTokenWithCredentials = "include";`).
