### ISSUE TITLE
Authorization should use completeInTarget by default

### ISSUE THREAD

**Issue by pgross41** [smart-on-fhir/client-js#89]
The default authorization options create a logical path that leads to a dead end when loading inside an iframe. 

Example: Assume blue is the main app and yellow is a child SMART on FHIR app in an iframe. The authorization options are typed out for clarity but those values match the default values. 

![image](https://user-images.githubusercontent.com/11710621/90094261-1672b000-dcf3-11ea-98f0-827721d75000.png)

Everything runs smoothly until it tries to send "completeAuth" to the parent [here](https://github.com/smart-on-fhir/client-js/blob/v2.3.1/src/smart.ts#L473). The parent is not SMART nor on FHIR so the message is never [received](https://github.com/smart-on-fhir/client-js/blob/v2.3.1/src/smart.ts#L402) and it silently stops authorizing. 

This can be avoided by setting `completeInTarget: true` but it took 2 days of digging to determine that. Silent failures are difficult to troubleshoot and defaulting to `true` will add iframe support out-of-the box. It is also intuitive that selecting a target will authorize in it, otherwise where is it authorizing?

**Comment by nakker** [comment]
Same problem here -- see this post as well https://github.com/smart-on-fhir/client-js/issues/75

I've suggested adding more documentation around this parameter since it presumably must be set for all Epic EHR launch situations.

**Comment by vlad-ignatov** [comment]
There is infinite number of combinations here. The most common use case of this was to enable authorizing in popup dialogs that would then close themselves and the app would be rendered in the opener. That is why `completeInTarget` defaults to false.

See some [examples](https://fmv99.csb.app/) (including an iframe that is in a popup)

At the same time, this had to be a backwards-compatible feature, so `target` and `completeInTarget` had to remain optional and older apps should continue to work as usual. Everything seems to work fine, except for the special case that you struggle with. That happens when the entire app happens to be loaded in an iframe rendered from another origin which was not the app developer's intention... The only remedy in this case is to explicitly set `completeInTarget: true`.

I have a new version that tries to somewhat improve this:
1. `completeInTarget` will default to `true` if `authorize` is called within an iframe
2. If `completeInTarget` is not provided and the app is loaded in an iframe or popup, a console warning will be used to advise devs to add `completeInTarget` to their authorize options.

This is yet to be released but if you want to give it a try, use `npm i fhirclient@dev` or link/download from https://combinatronics.com/smart-on-fhir/client-js/master/dist/build/fhir-client.js

**Comment by vlad-ignatov** [comment]
The fix is now released in `2.3.5`. Feel free to reopen if it does not solve the issue.
