### ISSUE TITLE
Getting invalid_client error for token request, installed fhir-client 2.3.5

### ISSUE THREAD

**Issue by Lakkanna** [smart-on-fhir/client-js#94]
Hi,
I'm getting invalid_client error, passing valid client id and redirect_uri still facing this issue

![image](https://user-images.githubusercontent.com/32791713/93017671-20384d80-f5e8-11ea-9ef2-2e40d3e06bb7.png)

**Comment by vlad-ignatov** [comment]
I'm sorry to hear that you have issues with this. Could you please provide more details so that I can try to reproduce this?
- Where are you connecting to (what are your `authorize` options)?
- Does this happen on launch, when `authorize` is called, or later when `refresh` is called?
- Are you getting any errors in the browser console?

You can also execute `localStorage.debug = "FHIR.*"` in the browser console and then reload and see if you get any useful info.

**Comment by Lakkanna** [comment]
Hi, the issue is fixed, there was issue in configuration

**Comment by imprasenjit** [comment]
Hi Lankana can you please guide how you resolved the problem @Lakkanna

**Comment by gowthaman1706** [comment]
Please tell the steps to resolve invalid client

**Comment by gowthaman1706** [comment]
> Hi,
> I'm getting invalid_client error, passing valid client id and redirect_uri still facing this issue
> 
> ![image](https://user-images.githubusercontent.com/32791713/93017671-20384d80-f5e8-11ea-9ef2-2e40d3e06bb7.png)

P

> Hi, the issue is fixed, there was issue in configuration

Please say the steps to resolve that issue

**Comment by novalagung** [comment]
hi @Lakkanna can you please elaborate more about the fix in the configuration? it will be very useful for many people including me

**Comment by novalagung** [comment]
Just wanted to share, for anyone who is looking for the solution, what to do to resolve the issue is simply wait for it for a few hours/day
